#!/usr/bin/env bash

echo "== delete-objects"

set -e

# Check for bucket name
if [ -z "$1" ]; then
    echo "Usage: ./delete-objects.sh my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1

# Delete all objects in the bucket
aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query 'Contents[].Key' \
--output text \
| tr '\t' '\n' \
| jq -Rn '{Objects: [inputs | {Key: .}]}' > /tmp/delete_objects.json

aws s3api delete-objects --bucket $BUCKET_NAME --delete file:///tmp/delete_objects.json