#!/usr/bin/env bash

echo "== delete--objects"

# Exit immediately if a command exits with a non-zero status
set -e


# Check for bucket name
if [ -z "$1" ]; then
    echo "There need to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi



BUCKET_NAME=$1

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME

aws s3api delete-objects --bucket $BUCKET_NAME 