#!/usr/bin/env bash

echo "== put object"

# Exit immediately if a command exits with a non-zero status
set -e


# Check for bucket name
if [ -z "$1" ]; then
    echo "There need to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi


# Check for filename
if [ -z "$2" ]; then
    echo "There need to be a filename  eg. ./bucket my-bucket-name my-file-prefix"
    exit 1
fi


BUCKET_NAME=$1
FILENAME=$2

OBJECT_KEY=$(basename "$FILENAME")

aws s3api put-object \
--bucket BUCKET_NAME \
--key $OBJECT_KEY \
--body $FILENAME