#!/usr/bin/env bash


# Where to store these files
output_dir="/temp/s3-bash-scripts"

# Output folder
mkdir -p "$output_dir"

# Generate a random number between 5 and 10
num_files=$((RANDOM % 6 + 5))

echo "Creating $num_files random files..."

for ((i=1; i<=$num_files; i++)); do
    # Generate a random filename
    random_filename="$output_dir/file_$i.txt"

    # Generate random data and write it to the file
    dd if=/dev/urandom of="$random_filename" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null

    echo "Created $random_filename"
done

echo "Done."