#!/usr/bin/env bash

echo "== sync"

# Exit immediately if a command exits with a non-zero status
set -e


# Check for bucket name
if [ -z "$1" ]; then
    echo "There need to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi


# Check for filename prefix
if [ -z "$2" ]; then
    echo "There need to be a filename prefix eg. ./bucket my-bucket-name my-file-prefix"
    exit 1
fi


BUCKET_NAME=$1
FILENAME_PREFIX=$2

# Where to store these files
OUTPUT_DIR="/tmp/s3-bash-scripts"

# Remove output directory if it exists (use -rf to avoid error if it doesn't exist)
rm -rf "$OUTPUT_DIR"

# Create output folder
mkdir -p "$OUTPUT_DIR"

# Generate a random number between 5 and 10
NUM_FILES=$((RANDOM % 6 + 5))

echo "Creating $NUM_FILES random files..."

for ((i=1; i<=$NUM_FILES; i++)); do
    # Generate a random filename
    FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"

    # Generate random data and write it to the file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null

    echo "Created $FILENAME"
done

echo "Done."

tree "$OUTPUT_DIR"

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files